### ISSUE TITLE
-W does not seem to work with "Could not match transformation" warning

### ISSUE THREAD

**Issue by mgeier** [felix-hilden/sphinx-codeautolink#100]
I don't know if this is an issue of `sphinx_codeautolink` or a Sphinx issue.

### Issue

Running Sphinx with `-W` exits with "success", even if a  "Could not match transformation" warning has been raised.

### Expected behavior

Sphinx should exit with "failure" (when `-W` is used), which in turn should mark CI jobs as "failed".

### Steps to reproduce

Example: https://github.com/AudioSceneDescriptionFormat/splines/runs/4827865837

Here we can also see that the warning message comes after the line

    The HTML pages are in _build/html.

**Comment by felix-hilden** [comment]
Oh damn, it probably is because the warning is issued in the cleanup step and not in the proper build. Unfortunately we can't do anything about it, since that's when the HTML is written. I'll have a look what Sphinx knows of this, if anything. Then we can ask the devs.

**Comment by felix-hilden** [comment]
Okay, here's the relevant function in Sphinx's source: [build](https://github.com/sphinx-doc/sphinx/blob/f38bd8e9529d50e5cceffe3ca55be4b758529ff7/sphinx/application.py#L326). It indeed seems that `build-finished` is emitted only at the very end of the process with no special handling. I'll post a question.

**Comment by felix-hilden** [comment]
In case you didn't follow the Sphinx issue: it's being fixed (although now stalled) on their end. So either the fix is eventually merged and released by Sphinx, or if not, then there's not much we can do about the warnings on our end. Because of that, I think I'll close this issue for housekeeping!
