### ISSUE TITLE
Build error on RTD

### ISSUE THREAD

**Issue by mgeier** [felix-hilden/sphinx-codeautolink#107]
Here's the log: https://readthedocs.org/projects/nbsphinx/builds/16789989/

Here's the error:

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/nbsphinx/envs/latest/lib/python3.7/site-packages/sphinx_codeautolink/extension/__init__.py", line 138, in merge_environments
    env.sphinx_codeautolink_transforms.update(
AttributeError: 'BuildEnvironment' object has no attribute 'sphinx_codeautolink_transforms'
```

Note that this happens on the second Sphinx call.

**Comment by felix-hilden** [comment]
Thanks for reporting, I'll have a look!

**Comment by felix-hilden** [comment]
RTD uses Sphinx's `SingleFileHTMLBuilder` as in their builds [here](https://github.com/readthedocs/readthedocs-sphinx-ext/blob/main/readthedocs_ext/readthedocs.py#L380). At least locally I can generate a single-file HTML just fine even after building ordinary documentation, and codeautolink is disabled then as expected. So I'm not sure how to start reproducing, but I'll read around some more and implement the env versioning regardless.

**Comment by felix-hilden** [comment]
Actually, it probably is because an env merge is attempted, but the env is never populated on a single-page build. So we should do nothing instead.

**Comment by felix-hilden** [comment]
I'm banking on that. @mgeier could you try the current master and see if it fixes the issue?

**Comment by felix-hilden** [comment]
A gentle ping, @mgeier, are you available in the near future to check this?

**Comment by mgeier** [comment]
Thanks for the reminder!

I created a version using the master branch on RTD and the error is gone!

See https://readthedocs.org/projects/nbsphinx/builds/16977328/

So I think this issue can be closed. Thanks a lot!

**Comment by felix-hilden** [comment]
Perfect, I'll cut a new release soon!

**Comment by mgeier** [comment]
Gentle reminder ... what about a new release?

**Comment by felix-hilden** [comment]
Apologies for the lack of clarity, I wanted to include #108 but I got caught up with IRL things and now I've been ill for a while. I'll try to work on it during the week.

**Comment by felix-hilden** [comment]
Released just now, thanks for your patience!

**Comment by mgeier** [comment]
Thanks a lot, much appreciated!
