### ISSUE TITLE
Conda-forge package ?

### ISSUE THREAD

**Issue by Zeitsperre** [felix-hilden/sphinx-codeautolink#111]
Hi @felix-hilden,

This is a really neat library, and I have many repositories that could benefit enormously from this functionality. I'm wondering if you would be interested in making this available via [`conda-forge`](https://conda-forge.org/). The benefit of conda-forge is it would make this package available as a compiled binary in the Anaconda ecosystem (and you'd also get another badge for your Readme!). Once it's in the conda-forge repository, upkeep is fully automated, so no extra work on your part!

If this is of interest to you, I would be willing to draft the PR and maintain the conda-forge package, with you listed as primary maintainer. Please let me know!

**Comment by felix-hilden** [comment]
Thank you for the suggestion! I'm interested, although please do take all the credit you can 😄 I don't really know anything about conda-forge. Does that require changes on our part (the PR you mentioned)? Is it overall a big task?

The readme badge will be immensely valuable for that *sweet street cred*! Nice 😜

**Comment by Zeitsperre** [comment]
That's great! Everyone loves badges! 

Anaconda/conda-forge is incredibly useful for ensuring that environments are reproducible across platforms and OSes. It's fantastic for containerization. And no, I don't imagine any changes will be needed here. If there's anything, I'll mention it in the conda-forge PR or in this issue.

I'll tag you on the PR when it's up. Best!

**Comment by Zeitsperre** [comment]
PR is up! https://github.com/conda-forge/staged-recipes/pull/20403
