### ISSUE TITLE
BeautifulSoup minimum version

### ISSUE THREAD

**Issue by boxed** [felix-hilden/sphinx-codeautolink#128]
Hi, I tried codeautolink on iommi, and I got "Could not match a code example to HTML" on most things. After a lot of digging I found that this line in `link_html`:

```py
unique_blocks = {b.sourceline: b for b in blocks}.values()
```
is the problem for me. The reason is that it correctly finds all the blocks, but `b.sourceline` is `None` on all of them, so the above set operation throws them all out except the last one whatever that happens to be. 

The `sourceline` attribute is new in beautiful soup 4.8.1, and I had 4.7.1. 

I guess this lib should have a minimum acceptable version of beautiful soup set!

**Comment by felix-hilden** [comment]
Oh, thank you for the report and especially for digging this deep 🙏 Indeed, I found the changelog entry too. Easy fix, and I'll actually publish a new version right now since we had a few other things lined up as well!

**Comment by felix-hilden** [comment]
Released now 🎉

**Comment by boxed** [comment]
Nice! Fast turnaround too. 

I still haven't gotten it to work for my project so you might get some more issues heh.

**Comment by felix-hilden** [comment]
😅 looking forward to it!
