### ISSUE TITLE
Rethink directive and option names

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/sphinx-codeautolink#27]
I didn't give them much thought, but now would be the good time to change them since changes won't disrupt too many users.

- `codeautolink_autodoc_inject`: fine in my opinion
- `code-refs`: meh, could be `example-links` or `code-examples`
- `concat-blocks`: fine, but it's a bit ambiguous to a reader that doesn't know it's from this extension. Could be confused to *actually* concatenating code blocks.
- `implicit-import`: descriptive once you know it, but again I feel like this could be confusing at first
- `autolink-skip`: absolutely fine

**Comment by felix-hilden** [comment]
`codeautolink_default_import` is about to be a thing in #31, and Zac suggested a better name could be `codeautolink_block_prelude`. Ideally it would be similar to `implicit-import` (or what we change it to) in some way.

Let's make sure to get these changes in before the next release so default imports only exist with one name.

**Comment by felix-hilden** [comment]
I'll let this sit overnight, but I think in the absence of other comments we'll go with:

- `.. autolink-examples::`
- `.. autolink-skip::`
- `.. autolink-concat::`
- `.. autolink-preface::`
- `codeautolink_global_preface`
- `codeautolink_autodoc_inject`

Consistency and explicitness is on point here in my opinion. But I'm *so* tempted to change it from "preface" to "prelude" though 😄

If possible, we could also allow the preface directive to contain multiple lines. There's no real reason for the single line restriction. And I think it is important to highlight (or not obscure the fact) that the global configuration preface is added to all blocks even if a preface is defined already.

**Comment by Zac-HD** [comment]
Those look great to me - thanks for putting the thought into good names so early 🥰
