### ISSUE TITLE
Decorators are not linked, emit `RuntimeWarning`

### ISSUE THREAD

**Issue by Zac-HD** [felix-hilden/sphinx-codeautolink#28]
```rst
.. code:: python

    from functools import lru_cache

    @lru_cache
    def f(x): pass

    @lru_cache(maxsize=None)
    def f(x): pass
```
would ideally have `lru_cache` autolinked when used as a decorator, but instead we get:
```
sphinx_codeautolink/extension/block.py:224: 
	RuntimeWarning: Could not match transformation of `lru_cache` 
	on source line 3 <or line 6> in document "example.html", source:

from functools import lru_cache

@lru_cache
def f(x): pass

@lru_cache(maxsize=None)
def f(x): pass
```

I'm running Python 3.8, sphinx-codeautolink 0.2.1

**Comment by felix-hilden** [comment]
Thanks for the report, I'll work on this today! It's most likely due to the assumptions in our matching regex 👍

**Comment by felix-hilden** [comment]
Should. Not. Have. Skipped. eyeballing the documentation. Now we have @ signs all over 😅 Also, we need stricter tests.
