### ISSUE TITLE
Default import statements

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/sphinx-codeautolink#31]
Discussed in #29: let's do it. I somewhat overlooked their utility in a bunch of small code blocks. The indirection is minimal, and any name clashes are resolved anyway. Perhaps something like:

```python
# conf.py
codeautolink_default_imports = ["import lib", "import lib.sub as s"]
```

As with `implicit-imports`, we'll not allow newlines in entries.

**Comment by felix-hilden** [comment]
Nah, we'll split the lines just to be nice 👍

**Comment by Zac-HD** [comment]
If it's not just a single import, let's name it accordingly - e.g. `codeautolink_block_prelude`

**Comment by felix-hilden** [comment]
That's a fun suggestion 😄 I kinda like it! But I think ideally this would also relate to `implicit-imports`. If you wouldn't mind we could continue the discussion in #27 where I'm about to rename a bunch of things. I'll add yours there, but for now I'll give it a similar "import" name.
