### ISSUE TITLE
Link import statements

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/sphinx-codeautolink#42]
Discussed in #29: we could also link import statements. It can only make things better. Let's do:

```python
import mod.sub  # mod.sub
import mod.sub as s  # mod.sub, not "as s"
from mod.sub import foo as f  # foo, not "as f"
from mod.sub import *  # nothing linked
```

**Comment by Zac-HD** [comment]
> ```python
> from mod.sub import foo as f  # foo, not "as f"
> from mod.sub import *  # nothing linked
> ```

Might as well link `mod.foo` in these cases too; it's not like we can run out of hyperlinks!
