### ISSUE TITLE
0.4.0: sphinx (4.2.0) warnings on man page build

### ISSUE THREAD

**Issue by kloczek** [felix-hilden/sphinx-codeautolink#53]
Looks like on generate module documentation is failing and prints some warnings
```console
[tkloczko@ss-desktop sphinx-codeautolink-0.4.0]$ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.2.0
making output directory... done
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://matplotlib.org/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 7 added, 0 changed, 0 removed
reading sources... [100%] release_notes
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/tkloczko/rpmbuild/BUILD/sphinx-codeautolink-0.4.0/docs/src/404.rst: WARNING: document isn't included in any toctree
done
writing... sphinx-codeautolink.1 { release_notes reference about examples example_library } failed

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 467, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: PrefaceMarker
The full traceback has been saved in /tmp/sphinx-err-0zz69rdx.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by felix-hilden** [comment]
Hi, it appears you are building manpages. This library [only supports HTML](https://sphinx-codeautolink.readthedocs.io/en/latest/#caveats)! I'll close the issue, but feel free to comment again if I'm just seeing things wrong.

**Comment by kloczek** [comment]
So does it mean that on rendering non-html that module can be removed from copy.py without any consequences?

**Comment by felix-hilden** [comment]
Actually, we ought to make sure that using our directives is a no-op for the folks that want to build both types of documentation. Was this what you were asking?

**Comment by kloczek** [comment]
Yep. :)

**Comment by kloczek** [comment]
Yes .. if that error is exact consequence of what you wrote.
Just tested othat on rendering html there is no tjat error.
Simple on packaging python modules I;m including all documentation as man page and roff format it is still basic U*nix documentation format.
Each time I'm adding only small patch to generate `python-<module_name>.3' man page.
For example for your module that patch looks like below:
```patch
--- a/docs/src/conf.py~ 2021-10-08 17:23:49.000000000 +0100
+++ b/docs/src/conf.py  2021-10-29 20:52:14.279659504 +0100
@@ -49,3 +49,14 @@
         objname='configuration value',
         indextemplate='pair: %s; configuration value'
     )
+
+# Man ------------------------------------------------------------------
+man_pages = [
+    (
+        'index',
+        'python-sphinx-codeautolink',
+        'sphinx-codeautolink Python Module Documentation',
+        author,
+        3,
+    )
+]
```
Wit that it is easy access to all modules ducuemntation by type in shell `man pytjon-<moduile_name>` or search for exact module man page by `man python-<tab><tab>`

**Comment by kloczek** [comment]
Just in case .. I'm not expecting include that patch as it is kind of whole distribution level customisation which someone may see as redundant/useless/whatever other reason :)

**Comment by felix-hilden** [comment]
I'm not entirely sure what you mean. Nevertheless, I verified that building our documentation with `make man` (generated with `sphinx-quickstart`) does not produce the error you describe. So this could be an issue with the way you call sphinx or your special configuration. To be honest I don't really understand much about it. Are you deliberately *adding* `sphinx-codeautolink` specifically when generating manpages?

**Comment by kloczek** [comment]
That makefile is redundant. Sphinx provides setuuptols plugin which pttrovides bassic infrastructure OOTB to build documentsation in any format if everything is correvtly implemented.
https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html
Using that I was able to generate documentation for ~half of my python rpm packages.
```console
[tkloczko@ss-desktop SPECS]$ grep %py3_build_sphinx_man python-*| wc -l; ls -1 python-*| wc -l
343
676
```
```console
[tkloczko@ss-desktop SPECS]$ rpm -E %py3_build_sphinx_man
\
        PBR_VERSION=%{version} \
        SETUPTOOLS_SCM_PRETEND_VERSION=%{version} \
        /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
```

**Comment by felix-hilden** [comment]
Should work now, thanks again for letting me know!
