### ISSUE TITLE
Intersphinx links are broken

### ISSUE THREAD

**Issue by OriolAbril** [felix-hilden/sphinx-codeautolink#56]
Not completely sure why, but intersphinx links only seem to work if present in a file a the doc home folder. If in `index` or `examples` page they do work, but if in `examples/function` or `api/module/class` they point to `doc_base_url/correct_intersphinx_link`. 

One example of this behaviour for example, the numpy module link points tot `https://arviz--1923.org.readthedocs.build/en/1923/https://numpy.org/doc/stable/reference/index.html#module-numpy`

**Comment by felix-hilden** [comment]
Oh right, I managed to reproduce! Thanks for reminding 👍

**Comment by felix-hilden** [comment]
Right, so the reason it happens is that a local link is produced if the document is in folders regardless of whether it is a reference to the local docs or through intersphinx. So we'll detect web links and it should work fine.
