### ISSUE TITLE
Error message for invalid syntax adds spurious parenthesis

### ISSUE THREAD

**Issue by rsokl** [felix-hilden/sphinx-codeautolink#70]
The following code block has a syntax error (`hydra-zen` *should* be `hydra_zen`)

```
.. code-block:: python

   from hydra-zen import builds
```

sphinx-codeautolink raises the following error:

Handler <bound method SphinxCodeAutoLink.parse_blocks of <sphinx_codeautolink.extension.SphinxCodeAutoLink object at 0x0000027020449520>> for event 'doctree-read' threw an exception (exception: invalid syntax (<unknown>, line 1) in document "how_to\partial_config"    
Parsed source in `python` block:
block source: from hydra-zen import builds)

The last line, `from hydra-zen import builds)`, has a spurious `)` in it. This leads the reader on a wild goose chase, since there is no `)`. It should simply read `from hydra-zen import builds`.

**Comment by felix-hilden** [comment]
Hmm, thanks for the note! I do agree. However, the parentheses are inserted by Sphinx. So maybe we should add a new line there. I think that's the best we can do.
