### ISSUE TITLE
Extension error: target in _resolve_assignment can be None

### ISSUE THREAD

**Issue by rsokl** [felix-hilden/sphinx-codeautolink#71]
Building [these docs on this branch](https://github.com/mit-ll-responsible-ai/hydra-zen/tree/docs-autolink/docs) produces and extension error:

Extension error (sphinx_codeautolink.extension):
Handler <bound method SphinxCodeAutoLink.parse_blocks of <sphinx_codeautolink.extension.SphinxCodeAutoLink object at 0x00000243526B94C0>> for event 'doctree-read' threw an exception (exception: 'NoneType' object has no attribute 'components')

The culprit appears to be this block of code

https://github.com/felix-hilden/sphinx-codeautolink/blob/0edeab9e8bf013befde181a1a284a80a213de891/src/sphinx_codeautolink/parse.py#L294-L301

`target` is `None` at runtime, causing line 295 to raise.

**Comment by felix-hilden** [comment]
Thanks for the report! What version are you running? I think a proper stack trace should be printed in the latest version.

**Comment by rsokl** [comment]
I am using `v0.6.0`. I tried noodling around with my docs a bit to simplify things, but I can't easily narrow down the culprit. Unfortunately, I can't spend much more time on this right now.

**Comment by felix-hilden** [comment]
No worries! I pushed an improvement to the error message which should help a lot in finding the source.

**Comment by rsokl** [comment]
This appears to be the culprit:

```
.. code-block:: pycon

   >>> from pathlib import Path 
   >>> def print_file(x: Path):
   ...     with x.open("r") as f: 
   ...         print(f.read())  
   
   >>> *_, latest_job = sorted((Path.cwd() / "outputs").glob("*/*"))
```

**Comment by felix-hilden** [comment]
Thanks! This was very easy to narrow down now that you provided the specific faulty example. I'll push a fix now.

**Comment by Zac-HD** [comment]
Super fast!  I wander over to report hitting this in Hypothesis, and you've already fixed it 🤩
