### ISSUE TITLE
Make the extension parallel_read_safe or declare that it's not

### ISSUE THREAD

**Issue by mgeier** [felix-hilden/sphinx-codeautolink#77]
This extension should use `parallel_read_safe` to tell Sphinx whether it can be used to read source files in parallel.

See https://www.sphinx-doc.org/en/master/extdev/index.html#extension-metadata.

### Issue

When running Sphinx with the `-j` option (https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-j), it shows a warning about the `sphinx_codeautolink` extension not specifying whether it supports parallel operation and therefore Sphinx doesn't do anything in parallel.

### Expected behavior

Ideally, the extension should work for parallel builds (there might be some changes necessary?) and should set `parallel_read_safe` to `True`.

If that's not possible, it should set `parallel_read_safe` to `False` to avoid the Sphinx warning.

### Steps to reproduce

Run Sphinx with `-j4` (or whatever number > 1).

**Comment by felix-hilden** [comment]
Thanks for starting the issue, I'll research the parallellism implications a bit and get back to this!

**Comment by felix-hilden** [comment]
Honestly, I can't tell. Sphinx's documentation talks about modifying the environment, but I suspect any state is problematic with subprocesses. So I think we'll take the easy way out just to be safe. A number of improvements we can make:

- Get rid of `once_on_doctree_resolved` and just use an event that is emitted once
- Use the Sphinx environment to save all state

**Comment by felix-hilden** [comment]
Unfortunately though, custom block parsers mess with Pickle when subprocesses are spawned. It doesn't affect imported parsing functions, which is nice, but I'd like it to work for any functions.

One option would be to just document this hiccup and go ahead regardless.

**Comment by felix-hilden** [comment]
Yeah honestly, I doubt there's much we can do. @mgeier if you have any input, feel free to shoot!

**Comment by mgeier** [comment]
> [...] custom block parsers mess with Pickle when subprocesses are spawned. [...] I doubt there's much we can do.

Yeah, that's just how Sphinx works.

> It doesn't affect imported parsing functions, which is nice,

I guess that's one of the aspects of #76.

> but I'd like it to work for any functions.

It would be nice, but IMHO not essential.

> One option would be to just document this hiccup and go ahead regardless.

Yeah, exactly!

Thanks for implementing parallel reading in #85, this works well for me!

**Comment by felix-hilden** [comment]
Glad to hear, let me know if you run into further issues with the new release!
