### ISSUE TITLE
Turn ParsingError exceptions into Sphinx warnings

### ISSUE THREAD

**Issue by mgeier** [felix-hilden/sphinx-codeautolink#86]
I have some code blocks that intentionally contain syntactically incorrect Python code (https://nbsphinx.readthedocs.io/en/0.8.7/allow-errors.html).

Right now, when using the `sphinx_codeautolink` extension, I'm getting an extension error.

This is of course very good in most cases, because it allows us to detect mistakes.
However, I would like to be able to ignore this in some cases.
This would be possible if those errors would be turned into Sphinx warnings.
And if those warnings have a `type` and `subtype`, they can be ignored while other warnings would still be active.

I think this would be consistent with similar errors like e.g. illegal reStructuredText syntax, which don't stop Sphinx processing and produce warnings instead.

BTW, warnings can easily be turned into errors with the `-W`flag.

**Comment by felix-hilden** [comment]
This seems reasonable on the surface, but I have a counter offer: how would you feel about ignoring those blocks explicitly with `..autolink-skip::`? That way ignoring such errors wouldn't mask unwanted failures either.

Do you have other use cases in mind that would benefit from this? I guess one benefit would be that we can go through all the examples and issue warnings instead of stopping at the first and raising.

**Comment by mgeier** [comment]
> how would you feel about ignoring those blocks explicitly with `..autolink-skip::`?

Yes, when using reST source files that would be a very good solution.

However, I'm talking about using Jupyter Notebooks as source files, in which case I would have to come up with a mechanism to insert those `.. autolink-skip::` directives programmatically, e.g. via cell tags or cell metadata.
This would certainly be doable, but IMHO that's too complicated (both to implement and to use) to be worth it.

> That way you wouldn't mask unwanted failures either.

Yeah, that would be a disadvantage of ignoring the whole class of warnings, but I would probably be willing to accept that in my case.

It would be a trade-off that users have to decide on their own.

> Do you have other use cases in mind that would benefit from this?

Not really. But it seems natural, since parsing errors in Sphinx typically raise warnings (if I'm not mistaken).

----

In my concrete case I've just removed the offending cells from the notebook (https://github.com/spatialaudio/nbsphinx/pull/616), so this isn't urgent for me.

But still, I think it would generally make sense to use warnings for parsing error.

**Comment by felix-hilden** [comment]
Fair enough, and I'm warming up to the idea of having warnings regardless of the Jupyter use case 👍 That'd leave ignoring warnings as the user's responsibility while also providing the info.

Implementation considerations remain, like how do we provide the current information for warnings. We could just propagate an exception as we do currently and convert it to a warning, but then we can't parse further examples in the same document. So we should probably pass all the necessary info into the parser and generate warnings there.

**Comment by mgeier** [comment]
Sounds good!

I agree that exceptions should not be used for warnings.

But you can probably use `node.document.reporter.warning('blah blah', base_node=node)`?

This would already automatically include the path to the source file and the line number (if available) in the warning message, is there any other info needed?

You could probably even include the offending code snippet with  `node.document.reporter.warning('blah blah', node, base_node=node)`.

I don't know whether any of this is an official API, but it seems to work ...

**Comment by mgeier** [comment]
I realized today that `node.document.reporter.warning()` is a feature of `docutils` and it doesn't support Sphinx's `type` and `subtype`.

However, that's no problem, we don't have to use it, we can just use the standard Sphinx way of creating warnings, something like this:

```python
from sphinx.util.logging import getLogger

...

logger = getLogger(__name__)

...

            logger.warning('blah blah', location=node, type='codeautolink', subtype='syntax_error')
```

**Comment by felix-hilden** [comment]
Thanks for digging! I'll have a look next week 👌🏿

**Comment by felix-hilden** [comment]
Yeah, now having implemented the warnings, using `location=node` seems like the most elegant way to go!
