### ISSUE TITLE
Support for Python's built-in functions (and types)

### ISSUE THREAD

**Issue by mgeier** [felix-hilden/sphinx-codeautolink#87]
I'm not sure how complicated this would be to implement, but it would be cool to have links to builtin functions as well.

Functions from the standard library already seem to work when using

```python
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
}
```

But builtin functions like `print()`, `int()`, `float()` etc. don't seem to be linked, even though they can be used with `intersphinx`.

**Comment by felix-hilden** [comment]
Could be worth a look! I'm away for the weekend but I'll have a go after. If it's not in the inventory, intersphinx's logic might reveal what's going on.

**Comment by felix-hilden** [comment]
Oh of course, they are not imported so we don't track them. So to make this work we would need to 1) keep a list of builtin names and 2) track that list given that no names shadow them.

**Comment by felix-hilden** [comment]
Some digging: builtins are listed in the object inventory as bare names with no module (like "builtins"), so with our current implementation there could be a chance that they are confused with top level modules. We get rid of most of the inventory information before processing, so that might contain what we need to differentiate between the two.

**Comment by felix-hilden** [comment]
And "keeping a list" of builtins is rather easy:

```python
import builtins
dir(builtins)
```

So we only need to figure out a way to track builtins only if they have inventory entries, or alternatively discard them afterwards.

**Comment by felix-hilden** [comment]
This does exclude some things like `__file__` which are documented but not considered builtins. I think that's currently fine.

**Comment by mgeier** [comment]
Thanks a lot for implementing this, it works nicely!
