### ISSUE TITLE
Turn RuntimeWarning into Sphinx warning?

### ISSUE THREAD

**Issue by mgeier** [felix-hilden/sphinx-codeautolink#89]
Is there a reason to use `warnings.warn(..., RuntimeWarning)` instead of Sphinx's own warning mechanism (https://www.sphinx-doc.org/en/master/extdev/logging.html)?

I didn't see those warnings locally (for some reason, I never really understood Python's warning system), and my CI passed (even though I turned Sphinx warnings into errors with `-W`), so I was quite surprised when I realized that some of the code autolinks didn't work!

See also #86.

**Comment by felix-hilden** [comment]
Honestly, I wasn't aware of the warning system, so we probably should use Sphinx tooling for that. I'll work on it after the holidays!

**Comment by felix-hilden** [comment]
@mgeier Have you encountered custom Sphinx warnings somewhere? I'm looking for an example implementation to see what kind of naming they have used in the warning type. Right now I'm thinking we use our own namespace `codeautolink.*` and have subtypes for different cases.

**Comment by mgeier** [comment]
I haven't encountered many custom warnings in the wild, but I have created some myself, e.g. in https://github.com/mgeier/sphinx-last-updated-by-git and https://github.com/spatialaudio/nbsphinx.

I think `codeautolink.*` would be a good namespace.

The built-in types are listed here: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-suppress_warnings
